name: Classically Trained for Modern Problems
url: https://eannefawcett.github.io/
description: Technical and Non-technical Talk

permalink: /:year/:month/:day/:title/
paginate: 25

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
