name: Elizabeth Anne Fawcett
url: https://eannefawcett.github.io/
description: Classically Trained for Modern Problems -- Technical and Non-technical Talk
paginator: eannefawcett content

permalink: /:year/:month/:day/:title/
paginate: 25

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
