name: Elizabeth Fawcett
url: https://eannefawcett.github.io/
description: 'Classically Trained for Modern Problems: Technical and Non-technical Talk'

permalink: /:year/:month/:day/:title/
paginate: 25

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

# style: [colors-dark.css]
